apiVersion: v1
kind: ServiceAccount
metadata:
  name: etl-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etl-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etl-role-binding
subjects:
- kind: ServiceAccount
  name: etl-service-account
roleRef:
  kind: Role
  name: etl-role
  apiGroup: rbac.authorization.k8s.io
