# Example configuration file for distributed-transformer

formats:
  csv:
    batch_size: 1024
    default_has_header: true
    schema_sample_size: 1000
    max_sample_bytes: 1048576  # 1MB
    delimiter: ','
    quote: '"'
  
  parquet:
    batch_size: 1024
    use_statistics: true
    row_group_size: 134217728  # 128MB
    compression: "snappy"
    page_size: 1048576  # 1MB
    dictionary_page_size: 2097152  # 2MB
  
  default:
    batch_size: 1024
    schema_sample_size: 1000

plugins:
  plugin_dir: "./plugins"
  enable_plugins: true
  load_timeout_secs: 30
  enable_hot_reload: false
  hot_reload_interval_secs: 60
  version_compatibility: "Major"
  plugin_configs:
    json_plugin:
      pretty_print: true
      max_nesting_depth: 100
    avro_plugin:
      use_schema_registry: false

storage:
  read_buffer_size: 8388608  # 8MB
  write_buffer_size: 8388608  # 8MB
  max_concurrent_requests: 10
  retry:
    max_retries: 3
    initial_delay_ms: 100
    max_delay_ms: 5000
    backoff_multiplier: 2.0

streaming:
  max_buffer_memory: 268435456  # 256MB
  buffer_pool_size: 32
  read_timeout_secs: 300
  write_timeout_secs: 300
  enable_backpressure: true
  max_in_flight_batches: 4

processing:
  max_memory_bytes: 1073741824  # 1GB
  use_memory_mapping: true
  parallel_threads: 8  # Adjust based on your CPU cores
